### ISSUE TITLE
Mise en page avec modification de couleurs 

### ISSUE THREAD

**Issue by Pascal-Linssen** [OGSteam/mod-hof#2]
Quand je veux modifier une couleur dans le menu administration /Export BBCode j'ai toutes les couleurs qui passe en aqua au moment de la sauvegarde et le BBcode Bug aussi

BBcode avant modif des couleurs 

[color=black]Mine de Métal[/color] [color=silver]24[/color] [color=yellow]uriel[/color]
[color=black]Mine de Cristal[/color] [color=silver]20[/color] [color=yellow]uriel, neo32[/color]

Aprés modif d'une couleur modification dans  Decoration des catégories

[color=]Mine de Métal[/color] [color=]24[/color] [color=]uriel[/color]
[color=]Mine de Cristal[/color] [color=]20[/color] [color=]uriel, neo32[/color]

**Comment by darknoon29** [comment]
@Pascal-Linssen Je ne retrouve pas le soucis après quelques modifications.

Dis moi si c'est mieux avec la dernière version.

**Comment by darknoon29** [comment]
Confirmé ok par @Pascal-Linssen
